In [26]:
import numpy as np

In [66]:
# My own function to achive the problem;

def get_powerMatrix(vector, length=0, increasing=False): #function definion
    final_list=[]
    m=0
    if length==0: #checking the length to be build
        for i in vector:
            temp_list=[]
            for le in range(0,len(vector)):
                temp_list.append(i**le) #Apending each element of the array.
            if increasing is False:
                temp_list.reverse() #checks the order and prepare the elements.
            final_list.append(temp_list)
            
    else:
        for i in vector:
            temp_list=[]
            for le in range(0,length):
                temp_list.append(i**le) #Apending each element of the array.
            if increasing is False:
                temp_list.reverse()     #checks the order and prepare the elements.           
            final_list.append(temp_list)
            
    return np.array(final_list) # Returns array.

in_vec=np.array([1,2,3,4,5])

print('\n Generate array with default length \n')
print(get_powerMatrix(in_vec)) # calling the function with default argument

print('\n Generate with specific length \n')
print(get_powerMatrix(in_vec,4)) # calling the function with size

print('\n Generate with increasing order \n')
print(get_powerMatrix(in_vec, increasing=True)) # calling the function with size and order Fasle to get N-i-1

print('\n Generate array with specific length and increasing order \n')
print(get_powerMatrix(in_vec,4,True))



 Generate array with default length 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]

 Generate with specific length 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Generate with increasing order 

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]

 Generate array with specific length and increasing order 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


In [64]:
#Getting the output with the build in function

in_vec=np.array([1,2,3,4,5])

print('\n Generate array with default \n')
print(np.vander(in_vec))

print('\n Generate array with specific length \n')
print(np.vander(in_vec,4))

print('\n Generate array with increasing order \n')
print(np.vander(in_vec,increasing=True))

print('\n Generate array with specific length and increasing order \n')
print(np.vander(in_vec,4,True))


 Generate array with default 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]

 Generate array with specific length 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Generate array with increasing order 

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]

 Generate array with specific length and increasing order 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
